controller_list:
  - name: fake_panda_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_joint
      - elbow_joint
      - pitch_joint
      - yaw_joint
      - roll_joint
      - gripper_joint
  - name: fake_panda_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_joint
      - finger_1_joint
      - finger_2_joint
initial:  # Define initial robot poses per group
  - group: panda_arm
    pose: forward