panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - elbow_joint
    - pitch_joint
    - yaw_joint
    - roll_joint
    - gripper_joint
  gains:
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1